name: deployment

on:
  workflow_dispatch:
     inputs : 
      region :
        description: "Enter your region name : "
        required: true  
        type: string    


env:
  BUCKET: parasnewbuc1
  TFSTATE_FILE: S3.tfstate
  aws_region: ${{ github.event.inputs.region }}

jobs:

  news3bucket :

      runs-on : ubuntu-latest

      steps:

        - uses: actions/checkout@v3

        - name: Terraform hashicorp setup

          uses: hashicorp/setup-terraform@v2

          # with:

            # terraform_version: 1.1.7



        - name: Configure AWS Credentials

          uses: aws-actions/configure-aws-credentials@v1

          with:

            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

            aws-region: ${{ env.aws_region }}



        - name: terraform init

          run: |

            cd module
            terraform init -reconfigure -backend-config="bucket=${{ env.BUCKET }}" -backend-config="key=${{ env.TFSTATE_FILE }}" -backend-config="region=${{ env.aws_region }}"


      

        - name: terraform plan

          run: |
            cd module
            terraform plan

        

        - name: terraform apply

          run: |
            cd module 
            terraform apply -auto-approve



  # upload_file:
  #   needs: news3bucket
  #   name: terraform
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: CheckOut
  #       uses: actions/checkout@v3
  #     - name: set up terraform hasicrop
  #       uses: hashicorp/setup-terraform@v1

  #       # with:
  #       #   terraform_version: 1.1.7


  #     - name: configure aws cridentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
  #         aws-region: ${{env.aws_region}}

  #     - name: terraform init
  #       run: |
        
  #         terraform init -reconfigure -backend-config="bucket=${{ env.BUCKET }}" -backend-config="key=${{ env.TFSTATE_FILE }}" -backend-config="region=${{ env.aws_region }}"
      
  #     - name: terraform plan
  #       run: |
  #         terraform plan

  #     - name: terraform apply
  #       run: |
  #         terraform apply -auto-approve


