# This is a basic workflow to help you get started with Actions

name: destroy

on:
  workflow_dispatch:
env:
  BUCKET: parasnewbuc
  TFSTATE_FILE: S3.tfstate
  aws_region: ap-south-1

jobs:
    destroy_bucket:
      name: destroy
      runs-on: ubuntu-latest
      steps:
        - name: CheckOut
          uses: actions/checkout@v3
        - name: set up terraform hasicrop
          uses: hashicorp/setup-terraform@v1

          # with:
          #   terraform_version: 1.1.7


        - name: configure aws cridentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ${{env.aws_region}}
  
        - name: terraform plan
          run: |
            terraform init -backend-config="bucket=${{ env.BUCKET }}" -backend-config="key=${{ env.TFSTATE_FILE }}" -backend-config="region=${{ env.aws_region }}"
            cd module
            terraform init
        - name: destroy
          run: |
            cd module
            terraform destroy -auto-approve

